name: sunrise.alarm
description: "Sunrise alarm"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependency_overrides:
  intl: any

dependencies:

  flutter_localizations:
    sdk: flutter



  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

  geolocator: ^10.1.1
  geocoding: ^2.1.1
  daylight:
    git:
      url: https://github.com/bluefireteam/daylight.git

  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.1.1
  auto_route: ^7.7.1
  url_launcher: ^6.1.14

  intl: ^0.19.0
  intl_utils: ^2.8.3

  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.3.2
  firebase_analytics: ^10.4.2

  retrofit: ^4.0.1
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1

  auto_size_text: ^3.0.0
  lottie: ^2.5.0
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.1
  google_fonts: ^5.1.0
  permission_handler: ^11.3.0
  package_info_plus: ^5.0.1
  flutter_alarm_background_trigger: 1.0.2
  logger: ^2.0.2+1
  vibration: ^1.8.4

dev_dependencies:
  flutter_gen: ^5.3.0
  flutter_gen_runner: ^5.3.0
  build_runner: ^2.2.0
  custom_lint:
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/audio/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora.ttf

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: pl # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
